// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdp_zs3E7lHkCJbQu7D-DK110gsHxo8Bc',
    appId: '1:586869266095:web:664fe3652cee085bb2a65a',
    messagingSenderId: '586869266095',
    projectId: 'seatbooking-e2ccd',
    authDomain: 'seatbooking-e2ccd.firebaseapp.com',
    storageBucket: 'seatbooking-e2ccd.firebasestorage.app',
    measurementId: 'G-S7F7REXQ54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8wWOqm9tEPYGCy4cCxPMpztifub4M41E',
    appId: '1:586869266095:android:b6fb05b870f29507b2a65a',
    messagingSenderId: '586869266095',
    projectId: 'seatbooking-e2ccd',
    storageBucket: 'seatbooking-e2ccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuf5dRCKpb32KwQrztrxSnpy-cHXahPKU',
    appId: '1:586869266095:ios:fdee433070b2c7adb2a65a',
    messagingSenderId: '586869266095',
    projectId: 'seatbooking-e2ccd',
    storageBucket: 'seatbooking-e2ccd.firebasestorage.app',
    iosBundleId: 'com.example.busBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuf5dRCKpb32KwQrztrxSnpy-cHXahPKU',
    appId: '1:586869266095:ios:fdee433070b2c7adb2a65a',
    messagingSenderId: '586869266095',
    projectId: 'seatbooking-e2ccd',
    storageBucket: 'seatbooking-e2ccd.firebasestorage.app',
    iosBundleId: 'com.example.busBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdp_zs3E7lHkCJbQu7D-DK110gsHxo8Bc',
    appId: '1:586869266095:web:7fe341d70ca3157ab2a65a',
    messagingSenderId: '586869266095',
    projectId: 'seatbooking-e2ccd',
    authDomain: 'seatbooking-e2ccd.firebaseapp.com',
    storageBucket: 'seatbooking-e2ccd.firebasestorage.app',
    measurementId: 'G-KHKYNKP9KR',
  );
}
